### ISSUE TITLE
ZeDMDWifi LNK2019 Error when compiling using libzedmd 0.4.0

### ISSUE THREAD

**Issue by gustavoalara** [PPUC/libzedmd#14]
When compiling the program I'm making using the new 0.4.0 libzedmd library, Visual Studio shows me the following error:

G:\Mejoras Frontends\Proyectos\RGBMatrixControl\out\build\x64-Debug\zedmd_static.lib(ZeDMDWiFi.obj) : error LNK2019: unresolved external symbol __imp_htons referenced in function "public: virtual bool __cdecl ZeDMDWiFi::Connect(char const *,int)" (?Connect@ZeDMDWiFi@@UEAA_NPEBDH@Z)

My CMakelist has the new libraries loaded, so I don't know why I'm having this error of the ZeDMDWifi part... Have I forgotten something?

![image](https://github.com/PPUC/libzedmd/assets/7902641/4df5172f-9ef6-48fe-bd0c-baa6392cc1a7)

**Comment by jsm174** [comment]
If you look at how the new test executable links, you'll see that you also need to link against ws2_32 on windows.

https://github.com/PPUC/libzedmd/blob/4bba84a95a0c65bd4b0adc27e37dc609eb7ac7b8/CMakeLists.txt#L185-L192
