### ISSUE TITLE
Issues with the new 0.4.0 version (No ready signal)

### ISSUE THREAD

**Issue by gustavoalara** [PPUC/libzedmd#16]
Hi again, and sorry for bothering you so much.

Whenever I use the pre-compiled 'zedmd_test' or compile it myself, upon launching it, ZeDMD only displays the test on the top quarter of the panel. After that, the panel turns black, and the command line shows the errors attached.

![image](https://github.com/PPUC/libzedmd/assets/7902641/b98e4cfb-e3e9-4739-88a7-999ff5d75da7)

**Comment by mkalkbrenner** [comment]
Did you notice that we changed the lib for the serial communication?
Unfortunately it has the same name as the old one.

**Comment by gustavoalara** [comment]
I,m using the libserialport64.dll that comes with your 0.4.0 release... is not correct?

**Comment by jsm174** [comment]
@gustavoalara - what version of zedmd are you running?

**Comment by gustavoalara** [comment]
The last release: 3.4.1

**Comment by jsm174** [comment]
okay, just wanted to double check. my panel is only 128x32 so I don't know if we needed to update the test app to handle the bigger displays.

**Comment by mkalkbrenner** [comment]
I just solved a serial buffer issue with ESP32.
Please try libzedmd v0.5.0 and ZeDMD v3.5.0.

**Comment by gustavoalara** [comment]
Hi Markus,

I've tried to update the ZeDMD today to the new 3.5.0 release without successful.

I've opened a ticket on the ZeDMD GitHub regarding these issue. No problems rolling back to 3.4.1.

**Comment by gustavoalara** [comment]
Hi Markus,

With the new 0.5.0 libzeedmd and 3.5.0 ZeDMD I can communicate with my application. So this issue can be closed
