### ISSUE TITLE
libzedmd library documentation

### ISSUE THREAD

**Issue by gustavoalara** [PPUC/libzedmd#7]
Hi,

I'm very interested in using your library for use in other arcade projects not related to Pinbal. Will you release some kind of documentation on how to implement the library and how to use the functions defined in it?

**Comment by mkalkbrenner** [comment]
I also plan to use ZeDMD HD as arcade marquee. But yes, documentation has to be added.

**Comment by gustavoalara** [comment]
Thanks a lot! That's my main idea, but your library offers a lot of possibilities!

**Comment by mkalkbrenner** [comment]
@gustavoalara I started some documentation:
https://ppuc.github.io/libzedmd/docs/html/class_ze_d_m_d.html

or in source:
https://github.com/PPUC/libzedmd/blob/main/src/ZeDMD.h

**Comment by gustavoalara** [comment]
Amazing!
